### PR TITLE
Support Github OIDC authentication

### PR DESCRIPTION
**Pull request by SemiConscious**
Hi There. First - thanks for creating this great action - it delivers very nearly everything we need right now, apart from this one little fix to allow us to stick to AWS best practice - auth onto AWS using the github OIDC provider (instead of IAM keys), and that's what this pull request is about.

I have made some minimal changes to the way AWS credentials are handled. There is a new input: `aws-session-token` which is added to the `AWS.Credentials` objects. If it's a non-zero length string, the `AWS.Credentials` object is cloned and returned as-is, instead of getting a new credentials object by using ID and Secret to authenticate the user, or assume the role. If there is nothing in `aws-session-token` the original flow is maintained. I believe this change will not harm existing configurations using v1.2.

I am using my forked and modified tree (this one) and it's working.

I hope this is useful and can eventually be merged. Let me know your thoughts.

A possible usability upgrade would be to detect if someone is using `aws-actions/configure-aws-credentials` and use the output or environment variables it generates directly, but I can't see a clean way to do that due to variables/env needing to be explicitly passed between workflow steps. Maybe you know how to do that.

All the best - Jim

### CODE REVIEW

**Comment by SemiConscious** [comment]
One thing - I did run `npm run format` and it has made quite a few whitespace and other trivial changes. Apologies for that.

**Comment by SemiConscious** [comment]
I'm happy to have a crack at it but I'm on uk time, so I'll have it for you
tomorrow am if that's ok?

**Comment by mahdi-torabi** [comment]
Yep. No rush!
Thanks again.

**Comment by SemiConscious** [comment]
Hmm I don't know why I'm getting conflicts, I merged from your latest main. I am going to close this and create a new PR

**Pull request closed without merging**
